# -*- coding: utf-8 -*-
"""MagicMethods.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19sQ1-iBOpx96J-Z21GukKaP46ZfWVO4P
"""

multiplication = []
def mul(num):
  for b in range(1, 11):
    print("{} * {}  =  {}".format(num,b,num*b))

mul(9)



