# -*- coding: utf-8 -*-
"""program.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19sQ1-iBOpx96J-Z21GukKaP46ZfWVO4P
"""

import multiplication
#mul2 = multiplication.mul(10)
print("Hello, I ama inside program.py")

